version: "3.9"

services:
  bot:
    build:
      context: .
    restart: always
    volumes:
      - .:/app
    environment:
      - BINANCE_API_KEY=${BINANCE_API_KEY}
      - BINANCE_API_SECRET=${BINANCE_API_SECRET}
      - DEBUG=${DEBUG}